<a href="https://colab.research.google.com/github/NickStitely/PyTorch/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro - Deep Learning with Pytorch

In [1]:
# Import PyTorch - PyTorch is a library that lets you do all kinds of deep learning things
# import numpy - numpy lists to see differences

import torch
import numpy as np

# Lists

In [6]:
# Create a python list
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [7]:
# Create a 2 dimensional python list
my_list2 = [[1,2,3,4,5], [1,2,3,4]]
my_list2

[[1, 2, 3, 4, 5], [1, 2, 3, 4]]

# Numpy Arrays

In [8]:
# Generate a random Numpy 2D Array with 3 rows and 4 columns
np1 = np.random.rand(3,4)
np1

array([[0.47427895, 0.048291  , 0.30505469, 0.98396513],
       [0.38332641, 0.17298656, 0.91945458, 0.27714547],
       [0.12533277, 0.92847598, 0.54299617, 0.08612361]])

In [9]:
np1.dtype

dtype('float64')

# Tensors

In [10]:
# Create a Tensor 2D Array with 3 rows and 4 columns
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-2.4688,  0.2340,  0.6530, -0.4720],
        [ 1.4514,  0.2108,  0.7543,  0.1029],
        [ 0.5495,  1.3188, -1.5211,  0.5389]])

In [11]:
tensor_2d.dtype

torch.float32

In [12]:
# Create a Tensor 3D Array with 2 x Arrays of 3 rows and 4 columns
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4743, 0.0483, 0.3051, 0.9840],
        [0.3833, 0.1730, 0.9195, 0.2771],
        [0.1253, 0.9285, 0.5430, 0.0861]], dtype=torch.float64)

# Tensor Operations

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Re-shape and View
my_torch = my_torch.reshape(2,5) # Re-shape to a 2D array with 2 rows and 5 columns
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
#Re-shape with unknown number of items
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
#Re-shape with unknow rows
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.reshape(-1, 5)
my_torch3

# my_torch3 = my_torch3.reshape(-1, -1) # Only one dimension can be inferred

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
# Use view to convert to 2x5 array
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [37]:
# Update the 1st index to something else, view what happens to my_torch6 that was created out of my_torch5
my_torch5[1] = 4141
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [38]:
# Slice the array prep
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
my_torch7[7]

tensor(7)

In [40]:
my_torch7[7].dtype

torch.int64

In [41]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [43]:
# Get the values in index 1 of each array
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [44]:
# Do the above but keep as a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math Operations